export const DEFAULT_PRESET: Record<string, unknown> = {
  // Motion
  zoom: 1.0,
  rot: 0.0,
  cx: 0.5,
  cy: 0.5,
  dx: 0.0,
  dy: 0.0,
  warp: 1.0,
  sx: 1.0,
  sy: 1.0,
  fZoomExponent: 1.0,
  fWarpScale: 1.0,
  fWarpAnimSpeed: 1.0,
  fDecay: 0.98,
  fShader: 0.0,

  // Wave
  nWaveMode: 0,
  fWaveAlpha: 80,
  fWaveScale: 1.0,
  fWaveSmoothing: 0.75,
  wave_r: 1.0,
  wave_g: 1.0,
  wave_b: 1.0,
  wave_x: 0.5,
  wave_y: 0.5,
  wave_mystery: 0.0,
  bWaveDots: 0,
  bWaveThick: 0,
  bAdditiveWaves: 0,
  bModWaveAlphaByVolume: 0,
  bMaximizeWaveColor: 0,

  // Color/FX
  fGammaAdj: 1.0,
  fVideoEchoZoom: 1.0,
  fVideoEchoAlpha: 0.0,
  nVideoEchoOrientation: 0,
  bTexWrap: 0,
  bDarkenCenter: 0,
  bRedBlueStereo: 0,
  bBrighten: 0,
  bDarken: 0,
  bSolarize: 0,
  bInvert: 0,

  // Borders
  ob_size: 0.0,
  ob_r: 0.0,
  ob_g: 0.0,
  ob_b: 0.0,
  ob_a: 0.0,
  ib_size: 0.0,
  ib_r: 0.0,
  ib_g: 0.0,
  ib_b: 0.0,
  ib_a: 0.0,

  // Code
  per_frame_init_eqs_str: '',
  per_frame_eqs_str: 'a.zoom = 1.005 + 0.02*a.bass_att;\na.warp = 0.5 + 0.3*a.mid_att;',
  per_pixel_eqs_str: '',
  warp_str: '',
  comp_str: '',
};
